Feature/automatic login if user is already logged in
SEEMADHAMI/project1 pull request #9
Opened 2023-01-10 14:33 UTC by SEEMADHAMI

2023-01-10 14:36 UTC, Hpaneru commented on lib/screens/login_screen.dart
> +  final _auth = FirebaseAuth.instance;
remove this initialization.

2023-01-10 14:36 UTC, Hpaneru requested changes
resolve the comments

2023-01-10 14:57 UTC, Hpaneru commented on lib/screens/signup_screen.dart
> +  FirebaseAuth _auth = FirebaseAuth.instance;
remove this from here as well

2023-01-11 05:36 UTC, SEEMADHAMI commented on lib/screens/signup_screen.dart
> +  FirebaseAuth _auth = FirebaseAuth.instance;
Removed

2023-01-11 05:46 UTC, Hpaneru approved these changes
LGTM

2023-01-11 05:46 UTC, merged